name: Cypress E2E + Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-group: [ui, api]

    steps:
      - name:  Checkout do projeto
        uses: actions/checkout@v4

      - name:  Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name:  Instalar dependências
        run: npm ci

      - name:  Rodar testes Cypress (${{ matrix.test-group }})
        run: npx cypress run --spec "cypress/e2e/${{ matrix.test-group }}/**/*"

      - name:  Salvar allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.test-group }}
          path: allure-results
          retention-days: 1

  generate-report:
    needs: cypress-run
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do projeto
        uses: actions/checkout@v4

      - name:  Baixar todos os allure-results
        uses: actions/download-artifact@v4
        with:
          path: combined-results
          pattern: allure-results-*
          merge-multiple: true

     
      - name:  Baixar histórico do GitHub Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      
      - name:  Restaurar history
        run: |
          if [ -d "gh-pages/history" ]; then
            mkdir -p combined-results/history
            cp -r gh-pages/history/* combined-results/history/
          fi

      - name: ☕ Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name:  Gerar Allure Report
        run: |
          npm install -g allure-commandline
          allure generate combined-results --clean -o allure-report

      - name:  Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      - name: 🔗 Mostrar Link do Relatório
        if: always()
        run: |
          echo "###  Relatório Allure Disponível!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo " https://andretcrs.github.io/cypress/" >> $GITHUB_STEP_SUMMARY